pipeline:
  name: wan2.1-t2v-1.3b
  dtype: torch.bfloat16
  path: /data1/lyf/Lab/DiffSynth-Studio/models
eval:
  num_steps: 50
  guidance_scale: 5.0
  protocol: fmeuler{num_steps}-g{guidance_scale}
  height: 480
  width: 832
  num_samples: 1
  benchmarks: []
  num_gpus: 1
  batch_size_per_gpu: 1
quant:
  calib:
    data: Ditto-1M
    path: datasets/torch.bfloat16/test/caches
    batch_size: 1
    num_workers: 1
    num_samples: 80
  wgts:
    calib_range:
      element_batch_size: 64
      sample_batch_size: 1
      element_size: 512
      sample_size: -1
    low_rank:
      sample_batch_size: 1
      sample_size: -1
    skips:
    - embed
    - transformer_norm
    - transformer_add_norm
    - attn_add
    - ffn_add
  ipts:
    calib_range:
      element_batch_size: 64
      sample_batch_size: 1
      element_size: 512
      sample_size: -1
    skips:
    - embed
    - transformer_norm
    - transformer_add_norm
    - attn_add
    - ffn_add
  opts:
    calib_range:
      element_batch_size: 64
      sample_batch_size: 1
      element_size: 512
      sample_size: -1
  smooth:
    proj:
      element_batch_size: -1
      sample_batch_size: 1
      element_size: -1
      sample_size: -1
    attn:
      sample_batch_size: 1
      sample_size: -1
    quant:
  enable_rotation: true
  rotation:
    random: false
    transforms:
      - attn_out_proj
      - ffn_down_proj
